package com.morgan.todo
//package names are all in small letters
//TODO(rename main package from com.Morgan.Todo -> com.morgan.todo)

import org.springframework.stereotype.Service
import java.util.*

@Service
class MessageService {

    // this hashmap is going to be a class variable
    val map = mutableMapOf<String, TodoDto>()

    // create a new function to save todos
    // this function takes the todo as a parameter and saves it to our internal map
    // and then returns the generated id from the generatedId() function on line 34.
    fun saveTodoItem(todo: TodoDto): String {
        val todoId = generateId()
        map[todoId] = todo
        return todoId
    }

    fun getAllTodos() = map.values.toList()

    fun getTodo(id: String): TodoDto = map[id] ?: TodoDto("hi, hi", "hi, hi")

    // this function generates and returns a random id for our todos
    // a random uuid can be generated by importing the class
    // import java.util.UUID (see line 5) ,
    // or you can import a wildcard (java.util.*) this automatically imports
    // every class in the package provided under java.util.
    fun generateId(): String {
        val todoId = UUID.randomUUID().toString()
        println("Generated UUID: $todoId")
        return todoId
    }

}